// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RegistrationLog struct {
	ID        int64
	UserID    string
	Event     string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           string
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
