// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package pgdb

import (
	"context"
)

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*) FROM notifications
`

func (q *Queries) CountNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotificationByEventID = `-- name: GetNotificationByEventID :one
SELECT id, event_id, user_id, kind, created_at
FROM   notifications
WHERE  event_id = $1
`

func (q *Queries) GetNotificationByEventID(ctx context.Context, eventID string) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByEventID, eventID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (event_id, user_id, kind)
VALUES ($1, $2, $3)
ON CONFLICT (event_id) DO NOTHING
`

type InsertNotificationParams struct {
	EventID string
	UserID  string
	Kind    string
}

// ON CONFLICT DO NOTHING gives idempotency under JetStream
// redelivery. The UNIQUE(event_id) index on notifications is the
// enforcement point — a re-ACKed message becomes a silent no-op.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification, arg.EventID, arg.UserID, arg.Kind)
	return err
}
