// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package pgdb

import (
	"context"
)

const addUser = `-- name: AddUser :exec
INSERT INTO users (id, name, email, password_hash)
VALUES ($1, $2, $3, $4)
`

type AddUserParams struct {
	ID           string
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.Exec(ctx, addUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE  id = $1
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash
FROM   users
WHERE  lower(email) = lower($1)
`

type GetUserByEmailRow struct {
	ID           string
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash
FROM   users
WHERE  id = $1
`

type GetUserByIDRow struct {
	ID           string
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password_hash
FROM   users
ORDER  BY id
LIMIT  $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID           string
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logRegistration = `-- name: LogRegistration :exec
INSERT INTO registration_log (user_id, event)
VALUES ($1, $2)
`

type LogRegistrationParams struct {
	UserID string
	Event  string
}

func (q *Queries) LogRegistration(ctx context.Context, arg LogRegistrationParams) error {
	_, err := q.db.Exec(ctx, logRegistration, arg.UserID, arg.Event)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET    name = $1,
       email = $2,
       password_hash = COALESCE(NULLIF($3::text, ''), password_hash)
WHERE  id = $4
RETURNING id, name, email, password_hash
`

type UpdateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
	ID           string
}

type UpdateUserRow struct {
	ID           string
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}
